const bcrypt = require("bcryptjs");

const defaultPasswordHash = bcrypt.hashSync("password123", 10);
const adityaPasswordHash = bcrypt.hashSync("aditya@123", 10);

const seedUsers = [
  {
    id: "user_manager_1",
    name: "Sarah Jenkins",
    email: "manager@company.com",
    password: defaultPasswordHash,
    rawPassword: "password123",
    role: "manager",
    department: "Engineering Lead & Product Manager",
    employeeCode: "MGR-001",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_emp_1",
    name: "Rahul Sharma",
    email: "rahul@company.com",
    password: defaultPasswordHash,
    rawPassword: "password123",
    role: "employee",
    department: "Mobile Frontend Engineer",
    employeeCode: "EMP-104",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_emp_2",
    name: "Alex Chen",
    email: "alex@company.com",
    password: defaultPasswordHash,
    rawPassword: "password123",
    role: "employee",
    department: "Backend & Cloud Engineer",
    employeeCode: "EMP-108",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_emp_3",
    name: "Priya Patel",
    email: "priya@company.com",
    password: defaultPasswordHash,
    rawPassword: "password123",
    role: "employee",
    department: "UI/UX & Design Systems",
    employeeCode: "EMP-112",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_emp_aditya",
    name: "Aditya Tiwari",
    email: "aditya@company.com",
    password: adityaPasswordHash,
    rawPassword: "aditya@123",
    role: "employee",
    department: "Full Stack React Native Developer",
    employeeCode: "EMP-200",
    avatar: "https://api.dicebear.com/7.x/avataaars/png?seed=AdityaTiwari",
    createdAt: new Date().toISOString(),
  },
];

const seedTasks = [
  {
    id: "task_1",
    title: "Build Login Screen with Glassmorphism",
    description: "Design and implement the authentication screen featuring frosted glass cards, glowing neon buttons, and JWT session handling.",
    assignedToId: "user_emp_1",
    assignedToName: "Rahul Sharma",
    assignedToAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    createdById: "user_manager_1",
    createdByName: "Sarah Jenkins",
    priority: "High",
    deadline: "2026-08-30",
    status: "In Progress",
    progress: 70,
    category: "Frontend UI",
    tags: ["React Native", "Expo", "Glassmorphism", "Auth"],
    totalHoursSpent: 7.5,
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task_2",
    title: "Implement REST Task CRUD Endpoints",
    description: "Create clean Express endpoints for Task creation, status updates, employee assignment, and work update logging with role-based JWT auth.",
    assignedToId: "user_emp_2",
    assignedToName: "Alex Chen",
    assignedToAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    createdById: "user_manager_1",
    createdByName: "Sarah Jenkins",
    priority: "High",
    deadline: "2026-08-28",
    status: "Completed",
    progress: 100,
    category: "Backend API",
    tags: ["Node.js", "Express", "REST API", "JWT"],
    totalHoursSpent: 7.5,
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task_3",
    title: "Design Dark Neomorphic App Badges & Icons",
    description: "Create glowing status badges (Pending, In Progress, Completed) and responsive visual components for mobile dashboards.",
    assignedToId: "user_emp_3",
    assignedToName: "Priya Patel",
    assignedToAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    createdById: "user_manager_1",
    createdByName: "Sarah Jenkins",
    priority: "Medium",
    deadline: "2026-09-02",
    status: "In Progress",
    progress: 45,
    category: "Design System",
    tags: ["UI/UX", "Figma", "Design Tokens"],
    totalHoursSpent: 2.5,
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task_4",
    title: "Firebase Firestore Sync & CLI Integration",
    description: "Set up Firestore security rules and serviceAccountKey configuration with seamless offline fallback for employers.",
    assignedToId: "user_emp_2",
    assignedToName: "Alex Chen",
    assignedToAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    createdById: "user_manager_1",
    createdByName: "Sarah Jenkins",
    priority: "Medium",
    deadline: "2026-09-05",
    status: "Pending",
    progress: 0,
    category: "Cloud Database",
    tags: ["Firebase", "Firestore", "DevOps"],
    totalHoursSpent: 0,
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task_aditya_1",
    title: "Finish the Application Development",
    description: "Complete the full-stack Employee Task Manager application: polish all React Native screens, finalize REST API endpoints, connect Firebase Firestore, integrate Live Chat with Manager moderation, implement password show/hide, employee creation portal, and deploy the working app to GitHub with full documentation.",
    assignedToId: "user_emp_aditya",
    assignedToName: "Aditya Tiwari",
    assignedToAvatar: "https://api.dicebear.com/7.x/avataaars/png?seed=AdityaTiwari",
    createdById: "user_manager_1",
    createdByName: "Sarah Jenkins",
    priority: "High",
    deadline: "2026-09-01",
    status: "In Progress",
    progress: 65,
    category: "Full Stack Development",
    tags: ["React Native", "Node.js", "Firebase", "Expo", "REST API", "Live Chat"],
    totalHoursSpent: 12.5,
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const seedUpdates = [
  {
    id: "update_1",
    taskId: "task_1",
    taskTitle: "Build Login Screen with Glassmorphism",
    userId: "user_emp_1",
    userName: "Rahul Sharma",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    note: "Built custom GlassCard container with backdrop blur and glow effects, set up Expo LinearGradient.",
    previousProgress: 0,
    newProgress: 40,
    hoursSpent: 3.5,
    isBlocker: false,
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "update_2",
    taskId: "task_1",
    taskTitle: "Build Login Screen with Glassmorphism",
    userId: "user_emp_1",
    userName: "Rahul Sharma",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    note: "Integrated JWT Auth Context and added smooth button press spring animations with one-click demo login.",
    previousProgress: 40,
    newProgress: 70,
    hoursSpent: 4.0,
    isBlocker: false,
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "update_aditya_1",
    taskId: "task_aditya_1",
    taskTitle: "Finish the Application Development",
    userId: "user_emp_aditya",
    userName: "Aditya Tiwari",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/png?seed=AdityaTiwari",
    note: "Completed all 6 screens with glassmorphic design system, psychological color palette, and spring animations. REST API backend with JWT auth working perfectly.",
    previousProgress: 0,
    newProgress: 40,
    hoursSpent: 5.5,
    isBlocker: false,
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "update_aditya_2",
    taskId: "task_aditya_1",
    taskTitle: "Finish the Application Development",
    userId: "user_emp_aditya",
    userName: "Aditya Tiwari",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/png?seed=AdityaTiwari",
    note: "Added Live Chat with Manager moderation (pin, delete, edit, emoji reactions), employee creation portal with random credential generation, and password show/hide animation.",
    previousProgress: 40,
    newProgress: 65,
    hoursSpent: 7.0,
    isBlocker: false,
    createdAt: new Date(Date.now() - 3600 * 1000).toISOString(),
  },
];

const seedMessages = [
  {
    id: "msg_1",
    channel: "general",
    userId: "user_manager_1",
    userName: "Sarah Jenkins",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    userRole: "manager",
    userDepartment: "Engineering Lead",
    text: "📢 Sprint Broadcast: Priority focus this sprint — authentication flow, real-time chat sync, and glassmorphic UI polish. Log daily updates before 6 PM.",
    isAnnouncement: true,
    isPinned: true,
    pinnedBy: "Sarah Jenkins",
    reactions: { "🚀": ["user_emp_1", "user_emp_2"], "👍": ["user_emp_3", "user_emp_aditya"] },
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: "msg_2",
    channel: "general",
    userId: "user_emp_aditya",
    userName: "Aditya Tiwari",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/png?seed=AdityaTiwari",
    userRole: "employee",
    userDepartment: "Full Stack Developer",
    text: "Hey team! I've completed the Live Chat moderation system and password show/hide animation. Currently working on the Manager employee onboarding portal. Progress is at 65%! 🔥",
    isAnnouncement: false,
    isPinned: false,
    reactions: { "🔥": ["user_manager_1", "user_emp_1"], "🚀": ["user_emp_2"] },
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: "msg_3",
    channel: "general",
    userId: "user_emp_1",
    userName: "Rahul Sharma",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    userRole: "employee",
    userDepartment: "Mobile Frontend",
    text: "Just pushed the spring micro-animations and glassmorphic button transitions. Task #1 is at 70%!",
    isAnnouncement: false,
    isPinned: false,
    reactions: { "👏": ["user_manager_1"] },
    createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
];

async function seedDatabase(database) {
  console.log("🌱 [Seed] Seeding users, tasks, updates and chat messages...");
  for (const user of seedUsers) await database.collection("users").doc(user.id).set(user);
  for (const task of seedTasks) await database.collection("tasks").doc(task.id).set(task);
  for (const update of seedUpdates) await database.collection("updates").doc(update.id).set(update);
  for (const msg of seedMessages) await database.collection("messages").doc(msg.id).set(msg);

  console.log(`✅ [Seed] Seeded:
  - ${seedUsers.length} Users (1 Manager, 4 Employees incl. Aditya Tiwari)
  - ${seedTasks.length} Tasks (incl. Aditya's "Finish the Application Development")
  - ${seedUpdates.length} Work Logs
  - ${seedMessages.length} Chat Messages`);
}

module.exports = { seedUsers, seedTasks, seedUpdates, seedMessages, seedDatabase };
